// Converts screenshots-src/<slug>/*.png into WebP (full + 640px) under public/screenshots
// and writes src/data/screenshots.gen.ts with each image's dimensions.
import sharp from 'sharp'
import fs from 'node:fs'
import path from 'node:path'

const SRC = 'screenshots-src'
const OUT = 'public/screenshots'
const MAX_WIDTH = 1600
const THUMB_WIDTH = 640

const manifest = {}
for (const slug of fs.readdirSync(SRC).sort()) {
  const dir = path.join(SRC, slug)
  if (!fs.statSync(dir).isDirectory()) continue
  fs.mkdirSync(path.join(OUT, slug), { recursive: true })
  manifest[slug] = {}
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.png')).sort()) {
    const name = file.replace(/\.png$/, '')
    const input = sharp(path.join(dir, file))
    const { width, height } = await input.metadata()
    const fullWidth = Math.min(width, MAX_WIDTH)
    const full = await input.clone().resize({ width: fullWidth }).webp({ quality: 80, effort: 6 }).toBuffer()
    const thumb = await input.clone().resize({ width: THUMB_WIDTH }).webp({ quality: 74, effort: 6 }).toBuffer()
    fs.writeFileSync(path.join(OUT, slug, `${name}.webp`), full)
    fs.writeFileSync(path.join(OUT, slug, `${name}-${THUMB_WIDTH}.webp`), thumb)
    manifest[slug][name] = { width: fullWidth, height: Math.round((height * fullWidth) / width) }
    console.log(`${slug}/${name}: ${(full.length / 1024).toFixed(0)}KB, thumb ${(thumb.length / 1024).toFixed(0)}KB`)
  }
}

const body = `// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export const THUMB_WIDTH = ${THUMB_WIDTH}

export const screenshotSizes = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, Record<string, { width: number; height: number }>>
`
fs.mkdirSync('src/data', { recursive: true })
fs.writeFileSync('src/data/screenshots.gen.ts', body)
