// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export const THUMB_WIDTH = 640

export const screenshotSizes = {
  "ember": {
    "cart": {
      "width": 1440,
      "height": 900
    },
    "checkout": {
      "width": 1440,
      "height": 900
    },
    "home": {
      "width": 1440,
      "height": 900
    },
    "mobile": {
      "width": 750,
      "height": 1624
    },
    "product": {
      "width": 1440,
      "height": 900
    },
    "shop": {
      "width": 1440,
      "height": 900
    }
  },
  "gamersense": {
    "champion": {
      "width": 1440,
      "height": 900
    },
    "features": {
      "width": 1440,
      "height": 900
    },
    "guess-rank-results": {
      "width": 1440,
      "height": 900
    },
    "guess-rank": {
      "width": 1440,
      "height": 900
    },
    "knowledge-hub": {
      "width": 1440,
      "height": 900
    },
    "landing": {
      "width": 1600,
      "height": 900
    },
    "mobile-landing": {
      "width": 750,
      "height": 1624
    },
    "profile": {
      "width": 1440,
      "height": 900
    },
    "scenarios": {
      "width": 1440,
      "height": 900
    }
  },
  "nour-clinic": {
    "admin-appointments": {
      "width": 1440,
      "height": 900
    },
    "admin-hours": {
      "width": 1440,
      "height": 900
    },
    "admin-overview": {
      "width": 1440,
      "height": 900
    },
    "booking": {
      "width": 1440,
      "height": 900
    },
    "confirmation": {
      "width": 1440,
      "height": 900
    },
    "home": {
      "width": 1440,
      "height": 900
    },
    "mobile-booking": {
      "width": 750,
      "height": 1624
    }
  },
  "pulse-analytics": {
    "customers-drawer": {
      "width": 1440,
      "height": 900
    },
    "login": {
      "width": 1440,
      "height": 900
    },
    "mobile-overview": {
      "width": 750,
      "height": 1624
    },
    "overview-dark": {
      "width": 1440,
      "height": 900
    },
    "overview-light": {
      "width": 1440,
      "height": 900
    }
  },
  "sahtein": {
    "hero-ar": {
      "width": 1296,
      "height": 810
    },
    "hero-en": {
      "width": 1296,
      "height": 810
    },
    "menu-ar": {
      "width": 1440,
      "height": 900
    },
    "mobile-menu": {
      "width": 750,
      "height": 1624
    },
    "reservation": {
      "width": 1440,
      "height": 900
    }
  }
} as const satisfies Record<string, Record<string, { width: number; height: number }>>
